[versions]
agp = "8.6.0"
android-compileSdk = "34"
android-minSdk = "21"
android-targetSdk = "34"

detekt = "1.23.7"
jetbrains-compose = "1.7.0"
kotlin = "2.0.21"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.9.3"
androidx-camera-camera2 = "androidx.camera:camera-camera2:1.3.4"
androidx-camera-lifecycle = "androidx.camera:camera-lifecycle:1.3.4"
androidx-camera-view = "androidx.camera:camera-view:1.3.4"
androidx-concurrent-futures = "androidx.concurrent:concurrent-futures-ktx:1.2.0"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.6"

detekt-compose = "io.nlopez.compose.rules:detekt:0.4.17"
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

koin-compose = "io.insert-koin:koin-compose:4.0.0"

kotlin-coroutines-swing = "org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.9.0"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
binary-compatibility = "org.jetbrains.kotlinx.binary-compatibility-validator:0.16.3"
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
m2p = { id = "io.github.composegears.m2p", version = "unspecified" }