name: Verify all platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  verify:
    name: Run detekt and build all platforms
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@v4

    - name: Check public API changes
      run: ./gradlew apiCheck

    - name: Execute Gradle build
      run: ./gradlew detekt

    - name: Build Android target
      run: ./gradlew example:app:composeApp:assembleDebug

    - name: Build Desktop target
      run: ./gradlew example:app:composeApp:package

    - name: Build Web target
      run: ./gradlew example:app:composeApp:wasmJsBrowserDistribution